console.log(Math.floor(202.49999));
console.log(Math.pow(20, 3.2));
console.log(Math.random());
console.log(Math.random() * 22);
let www = Math.random() * 22;
console.log(Math.floor(www));
console.log(Math.pow(Math.floor(www), 2));
var kkk = "Asqaraliyev Farrux";
console.log(kkk);
const tezlanish_formulasi = "a=F/m";
console.log(tezlanish_formulasi);
